-- ============================================================================
-- Script v2 — inclui:
--   1) As colunas do pacote anterior (16 mudanças) que ainda não foram
--      aplicadas nesse banco — é isso que estava causando os erros
--      "Invalid column name 'RECORRENTE'" etc.
--   2) Coluna nova MENSAGEM_CEFGA (OBS CEFGA) e DT_ULTIMA_CONFERENCIA.
--   3) As duas tabelas novas do log de conferência de campos (catálogo +
--      resultado por desembolso), seguindo o mesmo padrão de
--      CAD_TB003_VALIDACAO / CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO.
--   4) Seed do catálogo de campos conferíveis.
--   5) 2 desembolsos de teste (mock).
--
-- Todo o script é seguro pra rodar mais de uma vez (idempotente).
-- Rode conectado no database CadDesembolsoDev.
-- ============================================================================

USE [CadDesembolsoDev];
GO

-- ────────────────────────────────────────────────────────────────────────
-- 1) Colunas do pacote anterior (repetido aqui pra garantir que existam)
-- ────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'RECORRENTE')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [RECORRENTE] BIT NOT NULL CONSTRAINT DF_CAD_TB001_RECORRENTE DEFAULT (0);
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'TEM_CARROCERIA')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [TEM_CARROCERIA] BIT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'VEICULO_POSSUI_ADESIVOS')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [VEICULO_POSSUI_ADESIVOS] BIT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'CRP_NSA')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [CRP_NSA] BIT NOT NULL CONSTRAINT DF_CAD_TB001_CRP_NSA DEFAULT (0);
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'DATA_INICIO_OBRA')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [DATA_INICIO_OBRA] DATE NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'DESTINACAO_COLETA_RESIDUOS_SOLIDOS')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [DESTINACAO_COLETA_RESIDUOS_SOLIDOS] BIT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB002_CONTROLE_DESEMBOLSO') AND name = 'MOTIVO_CANCELAMENTO')
    ALTER TABLE [CAD_TB002_CONTROLE_DESEMBOLSO] ADD [MOTIVO_CANCELAMENTO] NVARCHAR(3000) NULL;
GO

-- ────────────────────────────────────────────────────────────────────────
-- 2) Colunas novas desta sessão
-- ────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB001_DESEMBOLSO') AND name = 'MENSAGEM_CEFGA')
    ALTER TABLE [CAD_TB001_DESEMBOLSO] ADD [MENSAGEM_CEFGA] NVARCHAR(3000) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('CAD_TB002_CONTROLE_DESEMBOLSO') AND name = 'DT_ULTIMA_CONFERENCIA')
    ALTER TABLE [CAD_TB002_CONTROLE_DESEMBOLSO] ADD [DT_ULTIMA_CONFERENCIA] DATETIME NULL;
GO

-- ────────────────────────────────────────────────────────────────────────
-- 3) Tabelas novas — log de conferência de campos "não-validação"
-- ────────────────────────────────────────────────────────────────────────
IF OBJECT_ID('CAD_TB005_CAMPO_CONFERENCIA') IS NULL
BEGIN
    CREATE TABLE [CAD_TB005_CAMPO_CONFERENCIA] (
        CO_CAMPO   INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CAD_TB005_CAMPO_CONFERENCIA PRIMARY KEY,
        CHAVE      NVARCHAR(100) NOT NULL,
        DE_CAMPO   NVARCHAR(500) NOT NULL,
        DT_CRIACAO DATETIME NOT NULL,
        DESATIVADO BIT NOT NULL CONSTRAINT DF_CAD_TB005_DESATIVADO DEFAULT (0)
    );
END
GO

IF OBJECT_ID('CAD_TB006_CONFERENCIA_CONTROLE_DESEMBOLSO') IS NULL
BEGIN
    CREATE TABLE [CAD_TB006_CONFERENCIA_CONTROLE_DESEMBOLSO] (
        CO_CONFERENCIA        INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CAD_TB006_CONFERENCIA_CONTROLE_DESEMBOLSO PRIMARY KEY,
        CO_CONTROLE_DESEMBOLSO INT NOT NULL,
        CO_CAMPO              INT NOT NULL,
        DE_CAMPO              NVARCHAR(500) NOT NULL,
        CO_SITUACAO           INT NOT NULL,
        MENSAGEM              NVARCHAR(1000) NULL,
        DT_CONFERENCIA        DATETIME NOT NULL,
        CONSTRAINT FK_CAD_TB006_CONTROLE_DESEMBOLSO FOREIGN KEY (CO_CONTROLE_DESEMBOLSO) REFERENCES [CAD_TB002_CONTROLE_DESEMBOLSO](CO_CONTROLE_DESEMBOLSO),
        CONSTRAINT FK_CAD_TB006_CAMPO_CONFERENCIA FOREIGN KEY (CO_CAMPO) REFERENCES [CAD_TB005_CAMPO_CONFERENCIA](CO_CAMPO)
    );
END
GO

-- ────────────────────────────────────────────────────────────────────────
-- 4) Seed do catálogo de campos conferíveis — CHAVE precisa bater
-- exatamente com as chaves do dicionário _regrasConferencia em
-- ControleAnaliseDesembolsoService.cs. Pra adicionar um campo novo no
-- futuro, insira aqui com uma CHAVE nova e implemente o case
-- correspondente no código — até lá ele aparece como "Pendente".
-- ────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'AgenteFinanceiro')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'AgenteFinanceiro', N'Agente Financeiro', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'CnpjAgenteFinanceiro')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'CnpjAgenteFinanceiro', N'CNPJ Agente Financeiro', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'MutuarioFinal')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'MutuarioFinal', N'Tomador/Mutuário', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'CnpjMutuarioFinal')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'CnpjMutuarioFinal', N'CNPJ Tomador/Mutuário', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'AgentePromotor')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'AgentePromotor', N'Agente Promotor', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'CnpjAgentePromotor')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'CnpjAgentePromotor', N'CNPJ Agente Promotor', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'Programa')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'Programa', N'Programa', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'CoGigov')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'CoGigov', N'GIGOV', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'MatriculaGestor')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'MatriculaGestor', N'Matrícula do Gestor', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'ContratoAf')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'ContratoAf', N'Contrato AF', GETDATE(), 0);
IF NOT EXISTS (SELECT 1 FROM [CAD_TB005_CAMPO_CONFERENCIA] WHERE CHAVE = N'DtEngenharia')
    INSERT INTO [CAD_TB005_CAMPO_CONFERENCIA] (CHAVE, DE_CAMPO, DT_CRIACAO, DESATIVADO) VALUES (N'DtEngenharia', N'Data de emissão da engenharia', GETDATE(), 0);
GO

-- ────────────────────────────────────────────────────────────────────────
-- 5) 2 desembolsos mock (status atual do enum: 1=PENDENTE, 2=ANALISAR,
-- 3=DESEMBOLSAR, 4=NEGAR, 5=FINALIZAR, 6=CANCELAR)
-- ────────────────────────────────────────────────────────────────────────
DECLARE @agora date = CAST(GETDATE() AS date);

INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, CO_CONTRATO_AO, CO_CONTRATO_AO_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c123901', N'1301', N'c300001', @agora, 1,
    N'0790001', N'01', N'', N'', 1, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Mock 1', N'11111111000191', N'Agente Promotor Mock 1', N'22222222000191',
    1, 0, @agora, 1, 0.0000,
    0, 55000.00, 0.00, 55000.00, 220000.00,
    11000.00, 231000.00, 0.00, 220000.00,
    0.00, 0.00, 11000.00
);
DECLARE @coDesembolsoMock1 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO)
VALUES (@coDesembolsoMock1, DATEADD(DAY, 2, @agora), 1);
DECLARE @coControleMock1 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControleMock1, DE_VALIDACAO, 0
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;


INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, CO_CONTRATO_AO, CO_CONTRATO_AO_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c123902', N'1302', N'c300002', @agora, 1,
    N'0790002', N'02', N'', N'', 0, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Mock 2', N'11111111000192', N'Agente Promotor Mock 2', N'22222222000192',
    0, 0, @agora, 1, 32.5000,
    0, 70000.00, 0.00, 70000.00, 280000.00,
    14000.00, 294000.00, 0.00, 280000.00,
    0.00, 0.00, 14000.00
);
DECLARE @coDesembolsoMock2 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO)
VALUES (@coDesembolsoMock2, DATEADD(DAY, 2, @agora), 2);
DECLARE @coControleMock2 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControleMock2, DE_VALIDACAO, 0
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;

GO

SELECT d.CO_DESEMBOLSO, d.CO_CONTRATO_AF + '-' + d.CO_CONTRATO_AF_DV AS Contrato, c.CO_STATUS_DESEMBOLSO AS Status
FROM [CAD_TB001_DESEMBOLSO] d
JOIN [CAD_TB002_CONTROLE_DESEMBOLSO] c ON c.CO_DESEMBOLSO = d.CO_DESEMBOLSO
WHERE d.CO_CONTRATO_AF IN (N'0790001', N'0790002')
ORDER BY d.CO_DESEMBOLSO;
