-- ============================================================================
-- Insere 2 desembolsos de teste com status ANALISAR (2) — aparecem no grupo
-- "Analisar" da Home, com checklist completo (copiado do catálogo ativo).
-- Rode conectado no CadDesembolsoDev.
-- ============================================================================

USE [CadDesembolsoDev];
GO

DECLARE @coDesembolso1 INT, @coControle1 INT;
DECLARE @coDesembolso2 INT, @coControle2 INT;

-- ── Desembolso 1 ──
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c200101', N'1001', N'c200105', CAST(GETDATE() AS date), 3,
    N'0700101', N'01', 0, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Alfa', N'11122233000101', N'Agente Promotor Alfa', N'22233344000101',
    0, 0, CAST(GETDATE() AS date), 0, 25.230,
    0, 963274.97, 0.00, 963274.97, 915111.22,
    48163.75, 49986278.10, 10962739.24, 39023538.86,
    5992200.00, 2199300.00, 3792900.00
);
SET @coDesembolso1 = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (
    CO_DESEMBOLSO, RESPONSAVEL_ANALISE, RESPONSAVEL_BAIXA, RESPONSAVEL_DESEMBOLSO, GESTOR,
    DT_PRAZO, CO_STATUS_DESEMBOLSO, DT_CONCLUSAO
) VALUES (
    @coDesembolso1, NULL, NULL, NULL, NULL,
    DATEADD(DAY, 2, CAST(GETDATE() AS date)), 2, NULL
);
SET @coControle1 = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle1, DE_VALIDACAO, 0
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;

-- ── Desembolso 2 ──
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c200102', N'1002', N'c200105', CAST(GETDATE() AS date), 2,
    N'0700102', N'02', 0, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Beta', N'11122233000102', N'Agente Promotor Beta', N'22233344000102',
    1, 0, CAST(GETDATE() AS date), 1, 40.000,
    1, 500000.00, 0.00, 500000.00, 475000.00,
    25000.00, 20000000.00, 7000000.00, 13000000.00,
    2500000.00, 1000000.00, 1500000.00
);
SET @coDesembolso2 = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (
    CO_DESEMBOLSO, RESPONSAVEL_ANALISE, RESPONSAVEL_BAIXA, RESPONSAVEL_DESEMBOLSO, GESTOR,
    DT_PRAZO, CO_STATUS_DESEMBOLSO, DT_CONCLUSAO
) VALUES (
    @coDesembolso2, NULL, NULL, NULL, NULL,
    DATEADD(DAY, 2, CAST(GETDATE() AS date)), 2, NULL
);
SET @coControle2 = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle2, DE_VALIDACAO, 0
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;

SELECT d.CO_DESEMBOLSO, c.CO_CONTROLE_DESEMBOLSO, d.MUTUARIO_FINAL, d.CO_CONTRATO_AF, c.CO_STATUS_DESEMBOLSO
FROM [CAD_TB001_DESEMBOLSO] d
JOIN [CAD_TB002_CONTROLE_DESEMBOLSO] c ON c.CO_DESEMBOLSO = d.CO_DESEMBOLSO
WHERE c.CO_CONTROLE_DESEMBOLSO IN (@coControle1, @coControle2);
GO
