-- ============================================================================
-- Cria 5 desembolsos de teste no CadDesembolsoDev, cobrindo os status:
--   1) Pendente          (CO_STATUS_DESEMBOLSO = 0 — recém-inserido, "Pendência" na Home)
--   2) Aguardando análise (CO_STATUS_DESEMBOLSO = 1 — grupo "Analisar" na Home)
--   3) DRP aguardando    (CO_STATUS_DESEMBOLSO = 2 — aparece na aba DRP, "Aguardando")
--   4) DRP concluída     (CO_STATUS_DESEMBOLSO = 3 — aparece na aba DRP, "Baixado")
--   5) Rejeitada         (CO_STATUS_DESEMBOLSO = 4 — grupo "Rejeitados" na Home)
--
-- Cada um vem com o checklist completo (CAD_TB004), puxado do catálogo real
-- (CAD_TB003_VALIDACAO) — sem isso os cards mostrariam "0 de 0" validações.
-- Se o catálogo ainda não foi seedado nesse banco, os INSERTs no bloco de
-- checklist simplesmente não inserem nada (sem erro).
--
-- Rode conectado no database CadDesembolsoDev.
-- ============================================================================

USE [CadDesembolsoDev];
GO

DECLARE @agora date = CAST(GETDATE() AS date);
DECLARE @matriculaCefga nvarchar(7) = N'c151896';

-- ────────────────────────────────────────────────────────────────────────
-- 1) PENDENTE — acabou de ser solicitada, ninguém mexeu ainda
-- ────────────────────────────────────────────────────────────────────────
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c123401', N'1001', N'c200001', @agora, 1,
    N'0700001', N'01', 1, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Teste 1', N'11111111000101', N'Agente Promotor Teste 1', N'22222222000101',
    1, 0, @agora, 1, 0.0000,
    0, 50000.00, 0.00, 50000.00, 200000.00,
    10000.00, 210000.00, 0.00, 200000.00,
    0.00, 0.00, 10000.00
);
DECLARE @coDesembolso1 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO)
VALUES (@coDesembolso1, DATEADD(DAY, 2, @agora), 0);
DECLARE @coControle1 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle1, DE_VALIDACAO, 0 -- Analisar (nada respondido ainda)
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;


-- ────────────────────────────────────────────────────────────────────────
-- 2) AGUARDANDO ANÁLISE — já rodou a validação automática, tem item pendente
-- ────────────────────────────────────────────────────────────────────────
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c123402', N'1002', N'c200002', @agora, 1,
    N'0700002', N'02', 0, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Teste 2', N'11111111000102', N'Agente Promotor Teste 2', N'22222222000102',
    0, 1, @agora, 2, 45.5000,
    0, 80000.00, 0.00, 80000.00, 300000.00,
    15000.00, 315000.00, 0.00, 300000.00,
    0.00, 0.00, 15000.00
);
DECLARE @coDesembolso2 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO)
VALUES (@coDesembolso2, DATEADD(DAY, 2, @agora), 1);
DECLARE @coControle2 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle2, DE_VALIDACAO, 0 -- Analisar (pendente de revisão manual)
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;


-- ────────────────────────────────────────────────────────────────────────
-- 3) DRP AGUARDANDO — aprovado, esperando a baixa da DRP
-- ────────────────────────────────────────────────────────────────────────
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c123403', N'1003', N'c200003', @agora, 1,
    N'0700003', N'03', 0, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Teste 3', N'11111111000103', N'Agente Promotor Teste 3', N'22222222000103',
    2, 0, @agora, 3, 100.0000,
    0, 60000.00, 0.00, 60000.00, 250000.00,
    12000.00, 262000.00, 0.00, 250000.00,
    0.00, 0.00, 12000.00
);
DECLARE @coDesembolso3 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO, RESPONSAVEL_ANALISE, RESPONSAVEL_DESEMBOLSO, DT_CONCLUSAO)
VALUES (@coDesembolso3, DATEADD(DAY, 2, @agora), 2, @matriculaCefga, @matriculaCefga, @agora);
DECLARE @coControle3 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle3, DE_VALIDACAO, 1 -- Aprovado (senão nunca chegaria em DRP)
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;


-- ────────────────────────────────────────────────────────────────────────
-- 4) DRP CONCLUÍDA — já baixada
-- ────────────────────────────────────────────────────────────────────────
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR
) VALUES (
    N'c123404', N'1004', N'c200004', @agora, 2,
    N'0700004', N'04', 0, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Teste 4', N'11111111000104', N'Agente Promotor Teste 4', N'22222222000104',
    3, 1, @agora, 3, 100.0000,
    0, 90000.00, 0.00, 90000.00, 400000.00,
    20000.00, 420000.00, 90000.00, 310000.00,
    0.00, 0.00, 20000.00
);
DECLARE @coDesembolso4 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO, RESPONSAVEL_ANALISE, RESPONSAVEL_DESEMBOLSO, MATRICULA_BAIXA, DT_CONCLUSAO)
VALUES (@coDesembolso4, DATEADD(DAY, 2, @agora), 3, @matriculaCefga, @matriculaCefga, @matriculaCefga, @agora);
DECLARE @coControle4 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle4, DE_VALIDACAO, 1 -- Aprovado
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;


-- ────────────────────────────────────────────────────────────────────────
-- 5) REJEITADA
-- ────────────────────────────────────────────────────────────────────────
INSERT INTO [CAD_TB001_DESEMBOLSO] (
    MATRICULA_SOLICITANTE, CO_GIGOV, MATRICULA_GESTOR, DT_SOLICITADO, NU_DESEMBOLSO,
    CO_CONTRATO_AF, CO_CONTRATO_AF_DV, PRIMEIRO_DESEMBOLSO, AGENTE_FINANCEIRO, CNPJ_AF,
    MUTUARIO_FINAL, CNPJ_MUTUARIO_FINAL, AGENTE_PROMOTOR, CNPJ_AGENTE_PROMOTOR,
    CO_PROGRAMA, ULTIMO_DESEMBOLSO, DT_ENGENHARIA, CO_SITUACAO_OBRA, PERCENTUAL_OBRA,
    CO_TIPO_DESEMBOLSO, SOLICITADO_VI, GLOSSADO_VI, ACEITO_VI, PARTICIPACAO_FGTS,
    CONTRAPARTIDA, VALOR_EMPRESTIMO, DESEMBOLSADO, SALDO_DESEMBOLSAR,
    CONTRAPARTIDA_ATUAL, INTEGRALIZADO, SALDO_INTEGRALIZAR, MOTIVO_REJEICAO
) VALUES (
    N'c123405', N'1005', N'c200005', @agora, 1,
    N'0700005', N'05', 1, N'Caixa Econômica Federal', N'00360305000104',
    N'Prefeitura Municipal Teste 5', N'11111111000105', N'Agente Promotor Teste 5', N'22222222000105',
    0, 0, @agora, 1, 0.0000,
    0, 40000.00, 0.00, 40000.00, 150000.00,
    7500.00, 157500.00, 0.00, 150000.00,
    0.00, 0.00, 7500.00, N'Documentação divergente do contrato AF — reenviar com CND/CRP atualizados.'
);
DECLARE @coDesembolso5 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB002_CONTROLE_DESEMBOLSO] (CO_DESEMBOLSO, DT_PRAZO, CO_STATUS_DESEMBOLSO, RESPONSAVEL_ANALISE, RESPONSAVEL_DESEMBOLSO, DT_CONCLUSAO)
VALUES (@coDesembolso5, DATEADD(DAY, 2, @agora), 4, @matriculaCefga, @matriculaCefga, @agora);
DECLARE @coControle5 int = SCOPE_IDENTITY();

INSERT INTO [CAD_TB004_VALIDACAO_CONTROLE_DESEMBOLSO] (CO_VALIDACAO, CO_CONTROLE_DESEMBOLSO, DE_VALIDACAO, SITUACAO)
SELECT CO_VALIDACAO, @coControle5, DE_VALIDACAO, 0 -- Analisar
FROM [CAD_TB003_VALIDACAO] WHERE DESATIVADO = 0;

GO

SELECT d.CO_DESEMBOLSO, d.CO_CONTRATO_AF + '-' + d.CO_CONTRATO_AF_DV AS Contrato, c.CO_STATUS_DESEMBOLSO AS Status
FROM [CAD_TB001_DESEMBOLSO] d
JOIN [CAD_TB002_CONTROLE_DESEMBOLSO] c ON c.CO_DESEMBOLSO = d.CO_DESEMBOLSO
WHERE d.CO_CONTRATO_AF IN (N'0700001', N'0700002', N'0700003', N'0700004', N'0700005')
ORDER BY d.CO_DESEMBOLSO;
